using System;

namespace ProjectEuler.Problems
{
    public static class Problem002
    {
        public static void Run()
        {
            // Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
            // 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
            // By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
            ulong sum = 0;
            ulong prevValue = 1;
            ulong nextValue = 2;

            while (nextValue < 4000000)
            {
                var value = nextValue;
                nextValue += prevValue;
                prevValue = value;

                if (value % 2 == 0)
                {
                    sum += value;
                }
            }

            Console.WriteLine(sum);
        }
    }
}